# Generated by Django 5.2.9 on 2025-12-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_connections',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
