# Generated by Django 5.2.9 on 2025-12-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mg', '0002_userprofile_active_connections_userprofile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
