# Generated by Django 5.2.9 on 2025-12-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_pro', '0004_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
